```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 패키지 로드
```{r, message=FALSE, warning=FALSE}
library(devtools)
library(regbook)
library(MASS)
library(dplyr)
library(tidyr)
library(scatterplot3d)
library(profmem)
```

# 과제1번
```{r}
casl_am_backfit <- function(X, y, maxit=10L, df)
  {
    p <- ncol(X)
    id <- seq_len(nrow(X))
    alpha <- mean(y)
    f <- matrix(0, ncol = p, nrow = nrow(X))
    models <- vector("list", p + 1L)
    for (i in seq_len(maxit))
    {
      for (j in seq_len(p))
      {
        p_resid <- y - alpha - apply(f[, -j], 1L, sum)
        id <- order(X[,j])
        models[[j]] <- smooth.spline(X[id,j], p_resid[id], df = df)
        f[,j] <- predict(models[[j]], X[,j])$y
      }
      alpha <- mean(y - apply(f, 1L, sum))
    }
    models[[p + 1L]] <- alpha
    return(models)
}
```

```{r}
casl_am_predict <- function(models, X_new)
{
p <- ncol(X_new)
f <- matrix(0, ncol = p, nrow = nrow(X_new))
for (j in seq_len(p))
{
f[,j] <- predict(models[[j]], X_new[,j])$y
}
y <- apply(f, 1L, sum) + models[[p + 1L]]
list(y=y, f=f)
}
```


## 데이터
```{r}
set.seed(123)

n <- 1000; p <- 4
X <- matrix(runif(n * p, min = -2, max = 2), ncol = p)
f1 <- cos(X[,1] * 4) + sin(X[,1] * 10) + X[,1]^(2) 
f2 <- -1.5 * X[,2]^2 + (X[,2] > 1) * (X[,2]^3 - 1)
f3 <- 0
f4 <- sign(X[,4]) * 1.5
f1 <- f1 - mean(f1); f2 <- f2 - mean(f2)
f3 <- f3 - mean(f3); f4 <- f4 - mean(f4)
y <- 10 + f1 + f2 + f3 + f4 + rnorm(n, sd = 1.2)

colnames(X) <- c("X1", "X2", "X3", "X4")
df <- data.frame(y, X)


X_test <- matrix(runif(50 * 4, min=-2, max=2), ncol = p) # test set, 50*4
X_test <- data.frame(X_test)
```

## 계산 시간 비교
```{r}
rbenchmark::benchmark(
  "casl" = {
    casl_fit <- casl_am_backfit(X, y, maxit = 1, df = 5)
  },
  
  "mgcv" = {
    mgcv_fit <- mgcv::gam(y~s(X1) + s(X2) + s(X3) + s(X4), data = df)
  },
  
  "gam" = {
    gam_fit <- gam::gam(y~gam::s(X1, 4) + gam::s(X2, 4) 
                        + gam::s(X3, 4) + gam::s(X4, 4), data = df)
  },
  replications = 10,
  columns = c("test", "replications", "elapsed", "relative", "user.self", "sys.self",
              "user.child", "sys.child")
)
```
gam, casl, mgcv의 gam 순으로 빠르다.

## 추정값 비교
```{r}
casl_pred <- casl_am_predict(casl_fit, X_test)
gam_pred <- predict(gam_fit, X_test)
mgcv_pred <- mgcv::predict.gam(mgcv_fit, newdata = X_test)

head(casl_pred$y)
```

```{r}
head(gam_pred)
```

```{r}
head(mgcv_pred)
```
예측값이 오차 1 정도 범위로 차이나고 거의 비슷한 결과가 도출되었다.

# 과제 2번

## 데이터, 15 col, 150,000 row
```{r}
n <- 150000 ; p <- 15
X <- matrix(runif(n * p, min = -2, max = 2), ncol = p)

f1 <- cos(X[,1] * 4) + sin(X[,1] * 10) + X[,1]^(2) 
f2 <- -1.5 * X[,2]^2 + (X[,2] > 1) * (X[,2]^3 - 1)
f3 <- 0
f4 <- sign(X[,4]) * 1.5

f5 <- sign(X[,5])
f6 <- abs(X[,6])
f7 <- X[,7]^2
f8 <- sin(X[,8] * 3) * X[,8]^2
f9 <- abs(X[,9]) + 1
f10 <- X[,10]^4
f11 <- -X[,11]
f12 <- X[,12]^3
f13 <- cos(X[,13]) * X[,13]^2
f14 <- sin(X[,14])
f15 <- cos(X[,15])
```

## Centering
```{r}
f1 <- f1 - mean(f1) ; f2 <- f2 - mean(f2) ; f3 <- f3 - mean(f3)
f4 <- f4 - mean(f4) ; f5 <- f5 - mean(f5) ; f6 <- f6 - mean(f6)
f7 <- f7 - mean(f7) ; f8 <- f8 - mean(f8) ; f9 <- f9 - mean(f9)
f10 <- f10 - mean(f10) ; f11 <- f11 - mean(f11) ; f12 <- f12 - mean(f12)
f13 <- f13 - mean(f13) ; f14 <- f14 - mean(f14) ; f15 <- f15 - mean(f15)
```

```{r}
y <- 10 + f1 + f2 + f3 + f4 + f5+ f6 + f7 + f8 + f9 + f10 + f11 + f12 + f13 + f14 + f15 + rnorm(n, sd = 1.2)

df2 <- data.frame(y, X)
```

## 시간 비교
```{r}
bam_time <- system.time(
mgcv::bam(y~s(X[,1]) + s(X[,2]) + s(X[,3]) + s(X[,4]) + s(X[,5])
          + s(X[,6]) + s(X[,7]) + s(X[,8]) + s(X[,9]) + s(X[,10])
          + s(X[,11]) + s(X[,12]) + s(X[,13]) + s(X[,14]) + s(X[,15]), data = df2)
)


gam_time <- system.time(
mgcv::gam(y~s(X[,1]) + s(X[,2]) + s(X[,3]) + s(X[,4]) + s(X[,5])
          + s(X[,6]) + s(X[,7]) + s(X[,8]) + s(X[,9]) + s(X[,10])
          + s(X[,11]) + s(X[,12]) + s(X[,13]) + s(X[,14]) + s(X[,15]), data = df2)
)
bam_time
```

```{r}
gam_time
```
시간은 gam이 bam보다 더 빠르다.

## 메모리 비교
```{r}
bam_mem <- profmem(
  mgcv::bam(y~s(X[,1]) + s(X[,2]) + s(X[,3]) + s(X[,4]) + s(X[,5])
            + s(X[,6]) + s(X[,7]) + s(X[,8]) + s(X[,9]) + s(X[,10])
            + s(X[,11]) + s(X[,12]) + s(X[,13]) + s(X[,14]) + s(X[,15]), data = df2)
)


gam_mem <- profmem(
  mgcv::gam(y~s(X[,1]) + s(X[,2]) + s(X[,3]) + s(X[,4]) + s(X[,5])
            + s(X[,6]) + s(X[,7]) + s(X[,8]) + s(X[,9]) + s(X[,10])
            + s(X[,11]) + s(X[,12]) + s(X[,13]) + s(X[,14]) + s(X[,15]), data = df2)
)

total(bam_mem)
```

```{r}
total(gam_mem)
```
메모리는 bam이 gam보다 작다. (bam이 메모리를 덜 사용한다.)
